### ISSUE TITLE
Wystawienie FV dla osoby bez NIP

### ISSUE THREAD

**Issue by kkraszy** [miwaniec/ifirma-api#2]
Witam,

Mam problem z wystawienie FV dla osoby bez NIP. 

Mimo że na pozycje do FV są poprawnie skonfigurowane (StawkaVat = 0.23 , TypStawkiVat = PRC)  Api zwraca błąd:

`IFirma Api Error: Podana stawka VAT przyjmuje nieprawidłową wartość; dopuszczalne są następujące kombinacje: {TypStawkiVat = 'ZW', StawkaVat = null}, {TypStawkiVat = 'PRC', StawkaVat = 0.00}, {TypStawkiVat = 'PRC', StawkaVat = 0.03}, {TypStawkiVat = 'PRC', StawkaVat = 0.05}, {TypStawkiVat = 'PRC', StawkaVat = 0.07}, {TypStawkiVat = 'PRC', StawkaVat = 0.08}, {TypStawkiVat = 'PRC', StawkaVat = 0.22}, {TypStawkiVat = 'PRC', StawkaVat = 0.23}.`

**Comment by miwaniec** [comment]
jest to błąd pochodzący z API iFirmy, proszę zweryfikować całą treść wysyłanego żądania, czy tam stawki są ok (lub ją wstawić, abym mógł pomóc). Można też to zapytanie podesłać do iFirmy

**Comment by kkraszy** [comment]
Po kontakcie z Ifirma okazało się ze wszystkie wartości float było  źle zaokrąglane (np. VAT 0.23 miał jeszcze bardzo wiele liczb po przecinku). Lokalnie nie miałem tego problemu wiec problem jest uzależniony od wersji i ustawień PHP.
Problem rozwiązałem dodając: 

ini_set('precision', 10);
ini_set('serialize_precision', 10);

przed wywołanie funkcji z API.
